services:
  - type: web
    name: opportunite-affaires
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: opportunite-db
          property: connectionString

databases:
  - name: opportunite-db
    plan: free
    databaseName: opportunite_affaires
